api_platform:
    title: Hello API Platform
    version: 1.0.0
    defaults:
        pagination_client_enabled: true
        pagination_client_items_per_page: true
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    collection:
        pagination:
            enabled_parameter_name: pagination
            items_per_page_parameter_name: itemsPerPage